Polymer general tasks
Java-Classes/Exlibris pull request #54
Opened 2018-03-27 14:41 UTC by YegorUdovchenko

In this PR we have done the next  tasks from Genereal Tasks  : 

- Create and customize polymer-starter-kit app and add package.json
-  Integrate <exlibris-app> component with redux library
- Configure application routing
- Add <app-header> .
- Add <app-drawer> with following items: All Books, Expected Soon, Borrowed Books, Reserved Books, Should Return Soon, Overdue

Our application now has the following routing:
 - /all-books
- /expected-soon
- /borrowed-books
- /reserved-books
- /should-return-soon
- /overdue

We have created <menu-item> web component for each item in the <app-drawer> and integrate it with each path from routing.  <menu-item> - a clickable area with title,  icon and the count number.

For mobile devices, the following feature was added:
- <app-header> will be transformed as follows: A title from selected <menu-tem> will be added in the <app-header> and an icon for the menu call appears next to this title.

On the PS our application looks like this:
![image](https://user-images.githubusercontent.com/33631944/37970792-024d75e2-31dd-11e8-9038-4aa5018d7efb.png)
On the mobile devices our application looks like this:
<img src="https://user-images.githubusercontent.com/33631944/37970845-2b5c0c0a-31dd-11e8-8fe1-18907faa7b9c.png" alt="alt text" width="200" height="400"><img src="https://user-images.githubusercontent.com/33631944/37970881-43979316-31dd-11e8-88c3-2678c6e6a1fc.png" alt="alt text" width="200" height="400">

2018-04-03 13:29 UTC, dkalinin requested changes
@YegorUdovchenko PTAL

2018-04-03 13:29 UTC, dkalinin commented on client-web/src/exlibris-app/exlibris-app.html
> +                        attr-for-selected="data-name"
Why `data-name`? `data-page` is more obvious.

2018-04-03 13:29 UTC, dkalinin commented on client-web/src/exlibris-app/menu/exlibris-menu-drawer.html
> +            _getSelectedTitle(e) {
Why do we need this? Just use route to identify title.

2018-04-03 13:29 UTC, dkalinin commented on client-web/src/exlibris-app/menu/exlibris-menu-item.html
> +                margin: 4%;
Margin in % is a bad idea. Are you sure about it? Usually it's better to use px. https://www.hongkiat.com/blog/calculate-css-percentage-margins/

2018-04-03 13:29 UTC, dkalinin commented on client-web/src/exlibris-app/menu/exlibris-menu-item.html
> +                cursor: pointer;
Why? `<a>` is wrapping the item.

2018-04-03 13:29 UTC, dkalinin commented on client-web/src/exlibris-app/shell/redux-store.html
> +    };
`inititalState` and `reducer` will be also set to window. Use ES6 block scope: http://es6-features.org/#BlockScopedFunctions

2018-04-03 13:29 UTC, dkalinin commented on client-web/src/exlibris-app/shell/redux-store.html
> +    window.ReduxMixin = PolymerRedux(ExlibrisApp.store);
ReduxMixin should be also in application context.

2018-04-03 13:29 UTC, dkalinin commented on client-web/test/exlibris-app/exlibris-app_test.html
> +    });
`assert(test !== undefined)`

2018-04-03 13:29 UTC, dkalinin commented on client-web/test/exlibris-app/menu/exlibris-menu-drawer_test.html
> +        test('should set the selected item according to the passed value.', function () {
What about URL?

2018-04-03 13:29 UTC, dkalinin commented on client-web/test/exlibris-app/menu/exlibris-menu-item_test.html
> +<test-fixture id="TestFixtureWithParams">
This is not used.

2018-04-03 13:29 UTC, dkalinin commented on client-web/test/exlibris-app/menu/exlibris-menu-item_test.html
> +            assert.equal(badge.innerHTML, COUNT);
What was the element.count before set?

2018-04-04 08:14 UTC, YegorUdovchenko commented
@dkalinin PTAL

2018-04-05 08:47 UTC, dkalinin requested changes
Please merge the master branch. ESLint should warn about some global values in tests. `suite`, `test`, `flush`, `assert`, etc. should be added to globals in .eslintrc.json.

2018-04-05 08:47 UTC, dkalinin commented on client-web/test/exlibris-app/menu/exlibris-menu-drawer_test.html
> +            const selector = elementShadowRoot.querySelector(MENU_LIST_SELECTOR);
It's not a selector but some element.

2018-04-05 08:47 UTC, dkalinin commented on client-web/src/exlibris-app/exlibris-app.html
> +        class ExlibrisApp extends window.ExlibrisApplication.ReduxMixin(Polymer.Element) {
You can add ExlibrisApp to .eslintrc.json:
```json
"globals": {
  "ExlibrisApp": true
}
```
Then you can use it without window.

2018-04-05 08:47 UTC, dkalinin commented on client-web/test/exlibris-app/menu/exlibris-menu-item_test.html
> +            const badge = elementShadowRoot.querySelector('#menu-item-badge');
Selector can be a constant.

2018-04-05 08:47 UTC, dkalinin commented on client-web/src/exlibris-app/shell/redux-store.html
> +        ExlibrisApplication.initialState = initialState;
Why do you need reducer and initialState in application context?

2018-04-05 08:47 UTC, dkalinin commented on client-web/test/exlibris-app/menu/exlibris-menu-item_test.html
> +    suite('exlibris-menu-item', function () {
What about ESLint? It should throw an error about `suite`.

2018-04-05 08:47 UTC, dkalinin commented on client-web/test/exlibris-app/menu/exlibris-menu-item_test.html
> +        test('should display title and count badge.', function () {
What about ESLint? It should throw an error about `test`.

2018-04-05 08:47 UTC, dkalinin commented on client-web/test/exlibris-app/menu/exlibris-menu-item_test.html
> +            assert.equal(title.innerHTML, TITLE);
What about ESLint? It should throw an error about `assert`.

2018-04-05 09:02 UTC, dkalinin requested changes

2018-04-05 09:02 UTC, dkalinin commented on client-web/test/exlibris-app/menu/exlibris-menu-drawer_test.html
> +                    'actual: ' + actualRef + ', expected to end with: ' + expectedRef);
Assert error message should start with `Should`

2018-04-05 09:11 UTC, dkalinin requested changes

2018-04-05 09:11 UTC, dkalinin commented on client-web/src/exlibris-app/menu/exlibris-menu-drawer.html
> +         * How to use `<exlibris-menu-drawer>` component.
It's too obvious, no need to add such information to jsdoc.

2018-04-05 09:11 UTC, dkalinin commented on client-web/src/exlibris-app/menu/exlibris-menu-drawer.html
> +         * To make the selected menu item change style, bind the `selected` property.
It doesn't make sense.

2018-04-05 09:11 UTC, dkalinin commented on client-web/src/exlibris-app/menu/exlibris-menu-drawer.html
> +                --exlibris-menu-item-background-color: var(--exlibris-app-background-color);
Why not to make it default value in 'item' component?

2018-04-05 09:11 UTC, dkalinin commented on client-web/src/exlibris-app/menu/exlibris-menu-drawer.html
> +                --exlibris-menu-item-title-color: var(--app-secondary-color);
Why not to make it default value in 'item' component?

2018-04-05 12:17 UTC, YegorUdovchenko commented
@dkalinin PTAL

2018-04-06 09:15 UTC, dkalinin requested changes
@YegorUdovchenko PTAL

2018-04-06 09:15 UTC, dkalinin commented on client-web/src/exlibris-app/exlibris-app.html
>           * In typical use, just use `<exlibris-app>` at the top of your body:
just **add** `<exlibris-app>` **to** the top of your body:

2018-04-06 09:15 UTC, dkalinin commented on client-web/src/exlibris-app/menu/exlibris-menu-item.html
> +                cursor: pointer;
Again. `cursor: pointer;` is by default for `<a>` tag.

2018-04-06 09:15 UTC, dkalinin commented on client-web/src/exlibris-app/menu/exlibris-menu-item.html
> +                <slot name="icon"></slot>
Named slot is good when you have more than one slot. It's reduntant in this case.

2018-04-06 09:15 UTC, dkalinin commented on client-web/src/exlibris-app/menu/exlibris-menu-item.html
> +         * `--exlibris-menu-item-title-font-weight` | Item title font weight | normal
I see 2 css properties for the same thing: title. Maybe it's better to use css mixin?

2018-04-06 09:15 UTC, dkalinin commented on client-web/src/exlibris-app/shell/redux-store.html
> +        /*global Redux PolymerRedux ReduxMixin:true*/
ReduxMixin is not global. It's inside of ExlibrisApplication.
BTW I'd suggest more short naming: ExlibrisApp.

2018-04-06 09:15 UTC, dkalinin commented on client-web/test/exlibris-app/menu/exlibris-menu-drawer_test.html
> +                    actualRef + ' should end with: ' + expectedRef);
Message should start with `Should`. Here it starts with `actualRef `.

2018-04-06 12:34 UTC, YegorUdovchenko commented
@dkalinin PTAL

2018-04-10 17:48 UTC, dkalinin requested changes
@YegorUdovchenko PTAL

2018-04-10 17:48 UTC, dkalinin commented on client-web/src/exlibris-app/menu/exlibris-menu-item.html
>                  cursor: pointer;
Are you ignoring me?

2018-04-10 17:48 UTC, dkalinin commented on client-web/src/exlibris-app/menu/exlibris-menu-item.html
> +                <span id="menu-item-badge" class="item-font count-badge">[[count]]</span>
It's not useful to apply the same CSS mixin to title and count.

2018-04-10 17:48 UTC, dkalinin commented on client-web/src/exlibris-app/shell/redux-store.html
> +        window.ExlibrisApp = {};
https://github.com/Java-Classes/MealOrder/pull/48#discussion_r180501761

2018-04-11 07:35 UTC, YegorUdovchenko commented
@dkalinin PTAL

2018-04-11 07:51 UTC, YegorUdovchenko commented
![capture](https://user-images.githubusercontent.com/33632314/38603411-3fdcc08a-3d76-11e8-8512-4c453a8f42ab.PNG)

2018-04-11 08:22 UTC, dkalinin requested changes
@YegorUdovchenko PTAL

2018-04-11 08:22 UTC, dkalinin commented on client-web/src/exlibris-app/exlibris-app.html
> +         * @memberof ExlibrisApp
It could be if you assign ExlibrisMainApp to ExlibrisApp namespace.

2018-04-11 08:22 UTC, dkalinin commented on client-web/src/exlibris-app/menu/exlibris-menu-item.html
> +            <div id="menu-item-body">
It's not necessary for `id` to have a prefix of the component.

2018-04-11 08:22 UTC, dkalinin commented on client-web/src/exlibris-app/exlibris-app.html
> +<link rel="import" href="./shell/exlibris-app-namespace.html">
`app-namespace` should be the first import.

2018-04-11 08:31 UTC, dkalinin requested changes
@YegorUdovchenko PTAL

2018-04-11 08:31 UTC, dkalinin commented on client-web/index.html
> +        background-color: #eeeeee;
Do we need this? We are using `app-layout` styles.

2018-04-11 08:31 UTC, dkalinin commented on client-web/src/exlibris-app/exlibris-app.html
> +                --exlibris-app-background-color: var(--paper-grey-200);
https://github.com/Java-Classes/MealOrder/pull/53#discussion_r180504430

2018-04-11 08:31 UTC, dkalinin commented on client-web/src/exlibris-app/exlibris-app.html
> +                color: #fff;
Let's use paper-color.

2018-04-11 08:31 UTC, dkalinin commented on client-web/src/exlibris-app/menu/exlibris-menu-drawer.html
> +                color: #fff;
Let's use paper-color.

2018-04-11 08:31 UTC, dkalinin commented on client-web/src/exlibris-app/menu/exlibris-menu-drawer.html
> +                    font-weight: bold;
Let's use paper-color.

2018-04-11 09:56 UTC, YegorUdovchenko commented
@dkalinin PTAL

2018-04-11 10:57 UTC, YegorUdovchenko commented
@dkalinin PTAL

2018-04-12 09:50 UTC, dkalinin requested changes
@YegorUdovchenko PTAL

2018-04-12 09:50 UTC, dkalinin commented on client-web/src/exlibris-app/exlibris-app.html
> +                font-family: 'Roboto', 'Noto', sans-serif;
It's better to leave font-family in index.html

2018-04-12 09:50 UTC, dkalinin commented on client-web/wct.conf.json
> +    "sauce": {
Why do you use "sauce" config instead of local?

2018-04-12 10:52 UTC, YegorUdovchenko commented
@dkalinin PTAL

2018-04-12 12:56 UTC, dkalinin approved these changes
@YegorUdovchenko LGTM
Please fix the comment

2018-04-12 12:56 UTC, dkalinin commented on client-web/wct.conf.json
> +      "browsers": ["chrome", "firefox", "ie"]
Let's replace with `"browsers":["all"]`. It prevents fails on different platforms.

2018-04-12 13:09 UTC, merged